{
 "title": "Caddy",
 "tags": [
  "http",
  "caddy",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=~\"caddy.*\"},instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(caddy_http_requests_total, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{handler=\"vars\"}[5m])",
     "legendFormat": "Incoming"
    },
    {
     "expr": "rate(caddy_http_requests_total{handler=\"file_server\"}[5m])",
     "legendFormat": "File Server"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_request_errors_total{handler=\"vars\"}[5m]) / rate(caddy_http_requests_total{handler=\"vars\"}[5m])",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "p99 Request Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}) by (le))"
    }
   ]
  },
  {
   "title": "Median Response Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, caddy_http_response_size_bytes_bucket{method=\"GET\", handler=\"file_server\", code=\"200\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(caddy_http_requests_total{handler=~\"[[handler]]\"}[1m])) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Requests by Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(caddy_http_request_duration_seconds_count{handler=\"file_server\"}[1m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Requests In Flight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(caddy_http_requests_in_flight{handler=~\"[[handler]]\"}[1m])) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Requests by Status (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(caddy_http_request_duration_seconds_count{handler=\"file_server\"}[1m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Request Duration (percentile)",
     "type": "graph",
     "description": "A histogram of the round-trip request duration.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Request Duration (heatmap)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{handler=\"file_server\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Duration (percentile)",
     "type": "graph",
     "description": "A histogram of time-to-first-byte for responses.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(caddy_http_response_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(caddy_http_response_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(caddy_http_response_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(caddy_http_response_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(caddy_http_response_duration_seconds_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Response Size (percentile)",
     "type": "graph",
     "description": "A histogram of the size of the returned response body.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(caddy_http_response_size_bytes_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(caddy_http_response_size_bytes_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(caddy_http_response_size_bytes_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(caddy_http_response_size_bytes_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(caddy_http_response_size_bytes_bucket{handler=\"file_server\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  }
 ]
}